package sistemas.tallerpoo.visual;

import javax.swing.DefaultComboBoxModel;
import sistemas.tallerpoo.clasesLogicas.Paciente;
import sistemas.tallerpoo.datos.PacienteDatos;
import sistemas.tallerpoo.datos.HistoriaClinicaDatos;

/**
 * Ventana de formulario de Historia Clínica. Proporciona métodos para mostrar y
 * gestionar la información relacionada con la historia clínica de los
 * pacientes. Puede mostrar la historia clínica asociada a un paciente
 * seleccionado.
 *
 * Este formulario permite seleccionar un paciente y visualizar su historial
 * clínico. Puede utilizarse para mostrar el historial clínico de un paciente
 * mediante su identificación de dni.
 *
 */
public class FormularioHistoriaClinica extends javax.swing.JFrame {

    HistoriaClinicaDatos datos = new HistoriaClinicaDatos();
    DefaultComboBoxModel modelo = new DefaultComboBoxModel();

    /**
     * Constructor para crear una instancia de FormularioHistoriaClinica. Carga
     * el formulario de historias clínicas y establece su posición relativa en
     * la ventana. Llena el JComboBox con los DNIs de los pacientes y muestra el
     * nombre asociado al DNI seleccionado.
     */
    public FormularioHistoriaClinica() {
        initComponents();
        this.setLocationRelativeTo(null);
        jcDnis.setModel(modelo);
        for (Paciente p : new PacienteDatos().obtenerPacientes()) {
            jcDnis.addItem(String.valueOf(p.getDni()));
        }
        datos.mostrarNombre(jlNombre, jcDnis);

    }

    /**
     * Constructor para crear una instancia de FormularioHistoriaClinica con un
     * DNI específico. Utiliza el constructor predeterminado y selecciona un DNI
     * particular en el JComboBox.
     *
     * @param dni El DNI del paciente para seleccionar y mostrar su historial
     * clínico.
     */
    public FormularioHistoriaClinica(int dni) {
        this();
        jcDnis.setSelectedItem(String.valueOf(dni));
    }

    /**
     * Vacía los campos de texto en el formulario de Historia Clínica. Establece
     * en blanco los campos de texto para el lugar, resultados, diagnóstico y
     * médico.
     */
    private void vaciarCampos() {
        txtLugar.setText("");
        txtResultados.setText("");
        txtDiagnostico.setText("");
        txtMedico.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtResultados = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcDnis = new javax.swing.JComboBox<>();
        jcFechas = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Medico Encargado");

        txtMedico.setEditable(false);

        jLabel4.setText("Diagnostico");

        txtDiagnostico.setEditable(false);
        txtDiagnostico.setColumns(20);
        txtDiagnostico.setLineWrap(true);
        txtDiagnostico.setRows(5);
        txtDiagnostico.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDiagnostico);

        jLabel5.setText("Lugar de Atencion");

        txtLugar.setEditable(false);

        jLabel6.setText("Resultados de Estudios");

        txtResultados.setEditable(false);

        jLabel7.setText("Dni del Paciente");

        jLabel8.setText("Fechas de consulta");

        jcDnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDnisActionPerformed(evt);
            }
        });

        jcFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcFechasActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Nombre del Paciente");

        jlNombre.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcDnis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcFechas, 0, 191, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombre)
                            .addComponent(jLabel9))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcDnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addGap(34, 34, 34)
                .addComponent(jlNombre)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Se activa al seleccionar un DNI en el ComboBox correspondiente. Llena el
     * ComboBox de fechas con las fechas de historia clínica disponibles y
     * muestra el nombre del paciente.
     *
     * @param evt El evento generado al seleccionar un DNI en el ComboBox.
     */
    private void jcDnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDnisActionPerformed
        datos.llenarFechas(jcDnis, jcFechas);
        datos.mostrarNombre(jlNombre, jcDnis);
    }//GEN-LAST:event_jcDnisActionPerformed

    /**
     * Se activa al seleccionar una fecha en el ComboBox de fechas. Muestra la
     * historia clínica correspondiente a la fecha seleccionada. Si no hay
     * fechas disponibles, vacía los campos de texto.
     *
     * @param evt El evento generado al seleccionar una fecha en el ComboBox.
     */
    private void jcFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcFechasActionPerformed
        if (jcFechas.getItemCount() <= 0) {
            vaciarCampos();
            return;
        }
        datos.mostrarHistoriaClinica(txtLugar, txtResultados, txtMedico, txtDiagnostico, jcDnis, jcFechas);
    }//GEN-LAST:event_jcFechasActionPerformed

    /**
     * El método main es el punto de entrada del programa. Inicializa la ventana
     * de FormularioHistoriaClinica.
     *
     * @param args Los argumentos de la línea de comandos.
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioHistoriaClinica().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcDnis;
    private javax.swing.JComboBox<String> jcFechas;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtResultados;
    // End of variables declaration//GEN-END:variables
}
